# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
file_path = r"C:\Users\tinuo\OneDrive\Desktop\cities.csv"
df = pd.read_csv(file_path, index_col =0)
df.head()

,Country,Lat,Lng,Temperature (°F),Humidity,Wind Speed,Cloudiness
City,,,,,,,
Lumphat,KH,13.4878,106.9816,80.73,72,6.15,97
Cape Town,ZA,-33.9258,18.4232,61.21,81,10.36,75
Avarua,CK,-21.2078,-159.7750,78.85,69,14.97,20
Severo-Kuril'sk,RU,50.6789,156.1250,39.16,70,3.65,42
Roma,AU,-26.5833,148.7833,79.70,36,8.34,90

In [4]:
clean_citi = df.dropna()
clean_citi

,Country,Lat,Lng,Temperature (°F),Humidity,Wind Speed,Cloudiness
City,,,,,,,
Lumphat,KH,13.4878,106.9816,80.73,72,6.15,97
Cape Town,ZA,-33.9258,18.4232,61.21,81,10.36,75
Avarua,CK,-21.2078,-159.7750,78.85,69,14.97,20
Severo-Kuril'sk,RU,50.6789,156.1250,39.16,70,3.65,42
Roma,AU,-26.5833,148.7833,79.70,36,8.34,90
...,...,...,...,...,...,...,...
Merced,US,37.1666,-120.7516,70.03,57,3.76,1
Parkes,AU,-33.1333,148.1833,65.35,80,1.01,100
Diamantino,BR,-14.4086,-56.4461,72.91,82,1.83,96
Kulu,TR,39.0951,33.0799,51.80,85,1.86,23
Sangar,RU,63.9242,127.4739,17.94,93,8.66,100

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
#Configure gmaps.
gmaps.configure(api_key=g_key)

In [6]:
#Use the Lat and Lng as locations and Humidity as the weight.
locations = clean_citi[["Lat", "Lng"]]
 
humidity = clean_citi["Humidity"].astype(float)

In [7]:
# Add Heatmap layer to map:
fig = gmaps.figure()

heatmap_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)

fig.add_layer(heatmap_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [10]:
  # Zero cloudiness.
cloud_df = clean_citi[clean_citi["Cloudiness"] == 0]

#A max temperature lower than 80 degrees but higher than 70.
temp_df = cloud_df[(cloud_df["Temperature (°F)"] > 70) & (cloud_df["Temperature (°F)"] < 80)]

  # Wind speed less than 10 mph.
wind_df = temp_df[temp_df["Wind Speed"] < 10]


#Drop any rows with null values.
wind_df = wind_df.dropna()
wind_df

,Country,Lat,Lng,Temperature (°F),Humidity,Wind Speed,Cloudiness
City,,,,,,,
La Paz,MX,24.1667,-110.3000,77.25,66,5.53,0
Marsaxlokk,MT,35.8419,14.5431,76.08,88,9.22,0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure